/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/mcp-probe/wrangler.jsonc --include-runtime=false --strict-vars=false apps/mcp-probe/worker-configuration.d.ts` (hash: 93e76b6b3cba84725a4348a62f964195)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	PROBE_ORIGIN: string;
	APP_VERSION: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	OWNER_EMAIL: string;
	OWNER_OPAQUE_ID: string;
	ALLOWED_REDIRECT_URIS: string;
	REPLAY_GUARD: DurableObjectNamespace<import("./src/index").ReplayGuard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ReplayGuard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PROBE_ORIGIN" | "APP_VERSION" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "OWNER_EMAIL" | "OWNER_OPAQUE_ID" | "ALLOWED_REDIRECT_URIS">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}